# Site settings

url: "https://chipset95.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

google-tracking-id: "UA-69555022-1"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Kartik Arora"
lang: "en"
title: "{ Chipset }"
favicon: "/img/icon.ico"
description: "Kartik\'s personal site and blog"
keywords: "kartik, arora, personal, chipset, github, android, app developer"

################
# Intro layout #
################

black-favicon: ""
background-img: ""
me-img: "https://avatars3.githubusercontent.com/u/6591617"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True   # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 50      # Default 10
start-delay: 100    # Default 200
delete-delay: 2000  # Default 5000
lines:          # You can add HTML Tags in the Text
  - text: "The best thing about a <b>boolean</b> is even if you are wrong, you are only off by a <b>bit</b>!"
  - text: "It’s not a <b>bug</b> – it’s an <b>undocumented feature</b>!"
  - text: "In order to understand <b>recursion</b>, one must first <b>understand recursion</b>"
  - text: "<b><i>Linux<i></b> is Truth"
  - text: "Whoever said <i>money can't buy you happiness</i> obviously never bought themselves a <b>drum kit</b>"

########
# Blog #
########

post-preview-words: 30

paginate: 10

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
pinterest-share: True

disqus-shortname: "chipset95"

###############
# Life Events #
###############

events:
  - image: "/img/work/tt15.png"
    date: "TechTatva'15"
    description: "Team Lead for college techfest app.<br>Download App from <a href=\"https://play.google.com/store/apps/details?id=chipset.techtatva\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/chipset95/TechTatva\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/work/revels15.png"
    date: "Revels'15"
    description: "Android app for college cultural fest.<br>Download App from <a href=\"https://play.google.com/store/apps/details?id=chipset.revels\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/chipset95/Revels\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/work/default.png"
    date: "Potato Library"
    description: "Easy to use Utility library for Android.<br>Get it on <a href=\"https://github.com/chipset95/Potato-Library\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/work/cpp.png"
    date: "Started Coding"
    description: "TurboC++ 3, the first IDE I used. Marked the begining of my journey in the amazing world of programming"

# First image of the Career timeline
work-img: "/img/work/rma2.png"

##################
# Contact layout #
##################

email: "kartik_arora95@@yahoo.co.in"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/chipset95"
  - title: "twitter"
    url: "https://twitter.com/chipset95"
  - title: "youtube"
    url: "https://youtube.com/MrChipset95"
  - title: "linkedin"
    url: "https://in.linkedin.com/in/chipset"
  - title: "envelope"
    url: "mailto:kartik_arora95@yahoo.co.in"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/404.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
    About: 'about'
    Blog: 'blog'
    Contact: 'contact'
    Work: 'work'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", ".gitignore", "vendor", "README.md", "res/resume.pdf"]

gems: [jekyll-paginate]
